Repository readthedocs/readthedocs.org, pull requests merged in 2018-03, with the labels that each got.

#3633 formatting buttons in edit project text editor
  media/lib/markitup/jquery.markitup.js
  media/lib/markitup/jquery.markitup.pack.js
  media/lib/markitup/sets/default/images/bold.png
  media/lib/markitup/sets/default/images/clean.png
  media/lib/markitup/sets/default/images/image.png
  media/lib/markitup/sets/default/images/italic.png
  media/lib/markitup/sets/default/images/link.png
  media/lib/markitup/sets/default/images/picture.png
  media/lib/markitup/sets/default/images/preview.png
  media/lib/markitup/sets/default/images/stroke.png
  media/lib/markitup/sets/default/set.js
  media/lib/markitup/sets/default/style.css
  media/lib/markitup/sets/sphinx/editor.css
  media/lib/markitup/sets/sphinx/editor.js
  media/lib/markitup/sets/sphinx/images/bold.png
  media/lib/markitup/sets/sphinx/images/book_link.png
  media/lib/markitup/sets/sphinx/images/clean.png
  media/lib/markitup/sets/sphinx/images/code.png
  media/lib/markitup/sets/sphinx/images/h1.png
  media/lib/markitup/sets/sphinx/images/h2.png
  media/lib/markitup/sets/sphinx/images/h3.png
  media/lib/markitup/sets/sphinx/images/image.png
  media/lib/markitup/sets/sphinx/images/indent.png
  media/lib/markitup/sets/sphinx/images/italic.png
  media/lib/markitup/sets/sphinx/images/link.png
  media/lib/markitup/sets/sphinx/images/link_go.png
  media/lib/markitup/sets/sphinx/images/list-bullet.png
  media/lib/markitup/sets/sphinx/images/list-numeric.png
  media/lib/markitup/sets/sphinx/images/picture.png
  media/lib/markitup/sets/sphinx/images/preview.png
  media/lib/markitup/sets/sphinx/images/quotes.png
  media/lib/markitup/sets/sphinx/images/stroke.png
  media/lib/markitup/skins/markitup/images/bg-container.png
  media/lib/markitup/skins/markitup/images/bg-editor-bbcode.png
  media/lib/markitup/skins/markitup/images/bg-editor-dotclear.png
  media/lib/markitup/skins/markitup/images/bg-editor-html.png
  media/lib/markitup/skins/markitup/images/bg-editor-json.png
  media/lib/markitup/skins/markitup/images/bg-editor-markdown.png
  media/lib/markitup/skins/markitup/images/bg-editor-textile.png
  media/lib/markitup/skins/markitup/images/bg-editor-wiki.png
  media/lib/markitup/skins/markitup/images/bg-editor-xml.png
  media/lib/markitup/skins/markitup/images/bg-editor.png
  media/lib/markitup/skins/markitup/images/handle.png
  media/lib/markitup/skins/markitup/images/menu.png
  media/lib/markitup/skins/markitup/images/submenu.png
  media/lib/markitup/skins/markitup/style.css
  media/lib/markitup/skins/simple/images/handle.png
  media/lib/markitup/skins/simple/images/menu.png
  media/lib/markitup/skins/simple/images/submenu.png
  media/lib/markitup/skins/simple/style.css
  media/lib/markitup/templates/preview.css
  media/lib/markitup/templates/preview.html
  readthedocs/templates/projects/import_extra.html
  readthedocs/templates/projects/project_advanced.html
  readthedocs/templates/projects/project_create.html
  readthedocs/templates/projects/project_edit.html
Labels: Design, PR: work in progress

#3704 Add argument to skip errorlist through knockout on common form
  readthedocs/core/templates/core/ko_form_field.html
Labels: PR: ready for review

#2787 check for matching alias before subproject slug
  readthedocs/core/views/serve.py
  readthedocs/rtd_tests/tests/test_resolver.py
  readthedocs/rtd_tests/tests/test_subprojects.py
Labels: PR: ready for review

#3752 #3741: replaced Go Crazy text with Search
  readthedocs/templates/search/base_facet.html
  readthedocs/templates/search/elastic_project_search.html
  readthedocs/templates/search/elastic_search.html
  readthedocs/templates/search/search.html
Labels: PR: ready for review

#3726 Add eslint rules and fix errors
  .eslintrc
  readthedocs/builds/static-src/builds/js/detail.js
  readthedocs/core/static-src/core/js/autocomplete.js
  readthedocs/core/static-src/core/js/doc-embed/footer.js
  readthedocs/core/static-src/core/js/doc-embed/mkdocs.js
  readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
  readthedocs/core/static-src/core/js/doc-embed/search.js
  readthedocs/core/static-src/core/js/doc-embed/sphinx.js
  readthedocs/core/static-src/core/js/readthedocs-doc-embed.js
  readthedocs/core/static-src/core/js/sponsorship.js
  readthedocs/core/static-src/core/js/tasks.js
  readthedocs/gold/static-src/gold/js/gold.js
  readthedocs/projects/static-src/projects/js/import.js
  readthedocs/projects/static-src/projects/js/tools.js
Labels: PR: ready for review

#3755 Check for http protocol before urlize
  readthedocs/templates/core/project_detail_right.html
Labels: PR: ready for review

#3749 Changed 'Submit' text on buttons with something more meaningful
  readthedocs/templates/core/project_details.html
  readthedocs/templates/projects/domain_list.html
  readthedocs/templates/projects/integration_list.html
  readthedocs/templates/projects/project_advanced.html
  readthedocs/templates/projects/project_edit.html
  readthedocs/templates/projects/project_notifications.html
  readthedocs/templates/projects/project_redirects.html
  readthedocs/templates/projects/project_translations.html
  readthedocs/templates/projects/project_users.html
  readthedocs/templates/projects/project_versions.html
Labels: PR: ready for review

#3548 Filter by my own repositories at Import Remote Project
  readthedocs/builds/static/builds/js/detail.js
  readthedocs/core/static/core/css/badge_only.css
  readthedocs/core/static/core/css/theme.css
  readthedocs/core/static/core/font/FontAwesome.otf
  readthedocs/core/static/core/font/fontawesome-webfont.eot
  readthedocs/core/static/core/font/fontawesome-webfont.svg
  readthedocs/core/static/core/font/fontawesome-webfont.ttf
  readthedocs/core/static/core/font/fontawesome-webfont.woff
  readthedocs/core/static/core/js/autocomplete.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/core/static/core/js/site.js
  readthedocs/gold/static/gold/js/gold.js
  readthedocs/projects/static-src/projects/css/import.less
  readthedocs/projects/static-src/projects/js/import.js
  readthedocs/projects/static/projects/css/import.css
  readthedocs/projects/static/projects/js/import.js
  readthedocs/projects/static/projects/js/tools.js
  readthedocs/restapi/serializers.py
  readthedocs/restapi/urls.py
  readthedocs/restapi/views/model_views.py
  readthedocs/rtd_tests/tests/test_privacy_urls.py
  readthedocs/templates/projects/project_import.html
Labels: PR: ready for review

#3693 Always record the git branch command as success
  readthedocs/vcs_support/backends/git.py
Labels: Needed: more information, PR: work in progress

#3649 Project updated when subproject modified
  readthedocs/projects/models.py
  readthedocs/rtd_tests/tests/test_project_symlinks.py
  requirements/testing.txt
Labels: PR: ready for review

#3672 Add a sustainability API
  readthedocs/restapi/urls.py
Labels: Status: blocked

#3666 Upgrade django-pagination to a "maintained" fork
  readthedocs/settings/base.py
  requirements/pip.txt
Labels: PR: ready for review

#3472 Improve "Sharing" docs
  docs/business/sharing.rst
Labels: PR: ready for review, Status: blocked

#2916 Upgrade all packages using `pur` tool
  readthedocs/projects/models.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_project_symlinks.py
  requirements/pip.txt
Labels: PR: ready for review

#3243 Upgrade docker-py to its latest version (docker==3.1.1)
  readthedocs/doc_builder/environments.py
  readthedocs/rtd_tests/mocks/environment.py
  requirements/pip.txt
Labels: PR: ready for review

#3791 Allow members of "Admin" Team to wipe version envs
  .gitignore
  readthedocs/core/views/__init__.py
Labels: PR: ready for review

#3823 Reorder GSOC projects, and note priority order
  docs/gsoc.rst
Labels: PR: ready for review

#3828 Bump docker -> 3.1.3
  requirements/pip.txt
Labels: PR: ready for review

#3822 Autolint cleanup for #3821
  .isort.cfg
  readthedocs/vcs_support/backends/git.py
  readthedocs/vcs_support/base.py
Labels: PR: ready for review

#3831 Update instance and model when `record_as_success`
  readthedocs/doc_builder/environments.py
Labels: PR: ready for review

#3821 Add temporary method for skipping submodule checkout
  readthedocs/projects/models.py
  readthedocs/rtd_tests/tests/test_backend.py
  readthedocs/vcs_support/backends/git.py
  readthedocs/vcs_support/base.py
Labels: PR: ready for review

#3793 Save docker image hash to consider when auto wiping the environment
  readthedocs/doc_builder/environments.py
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: PR: ready for review

#3543 Task to remove orphan symlinks
  readthedocs/projects/tasks.py
  readthedocs/rtd_tests/tests/test_project_symlinks.py
  readthedocs/settings/base.py
Labels: PR: ready for review

#3490 Documentation for RTD context sent to the Sphinx theme
  docs/design/theme-context.rst
  docs/vcs.rst
Labels: Needed: design decision, PR: ready for review

#3446 Show link to docs on a build
  readthedocs/templates/builds/build_detail.html
Labels: PR: ready for review

#3533 Fix regex for public bitbucket repo
  readthedocs/projects/constants.py
  readthedocs/rtd_tests/tests/test_repo_parsing.py
Labels: Bug, PR: ready for review

#3813 Remove pinned CSS Select version
  requirements/deploy.txt
Labels: PR: ready for review

#3860 Fix up some of the logic around repo and submodule URLs
  readthedocs/core/validators.py
  readthedocs/rtd_tests/tests/test_backend.py
  readthedocs/rtd_tests/utils.py
  readthedocs/vcs_support/backends/git.py
Labels: PR: hotfix, PR: ready for review

#3843 Use gitpython to find a commit reference
  readthedocs/vcs_support/backends/git.py
  requirements/pip.txt
Labels: PR: hotfix
