Repository readthedocs/readthedocs.org, pull requests merged in 2018-04, with the labels that each got.

#3740 tests: mock test_conf_file_not_found filesystem access
  readthedocs/rtd_tests/tests/test_project.py
Labels: PR: ready for review

#3901 Resolve subproject correctly in the case of single version
  readthedocs/core/views/serve.py
Labels: Bug, PR: ready for review

#3908 Use new django celery beat scheduler
  readthedocs/settings/base.py
  requirements/pip.txt
Labels: PR: ready for review

#3907 Use a proper default for `docker` attribute on UpdateDocsTask
  readthedocs/projects/tasks.py
Labels: Enhancement, PR: ready for review

#3893 Organize logging levels
  readthedocs/builds/models.py
  readthedocs/builds/syncers.py
  readthedocs/core/management/commands/clean_builds.py
  readthedocs/core/management/commands/reindex_elasticsearch.py
  readthedocs/core/signals.py
  readthedocs/core/views/hooks.py
  readthedocs/doc_builder/environments.py
  readthedocs/oauth/services/base.py
  readthedocs/oauth/services/bitbucket.py
  readthedocs/oauth/services/github.py
  readthedocs/oauth/services/gitlab.py
  readthedocs/payments/forms.py
  readthedocs/projects/search_indexes.py
  readthedocs/projects/tasks.py
  readthedocs/projects/views/base.py
  readthedocs/projects/views/private.py
  readthedocs/restapi/views/model_views.py
  readthedocs/rtd_tests/tests/test_privacy.py
  readthedocs/rtd_tests/utils.py
  readthedocs/search/parse_json.py
  readthedocs/search/utils.py
  readthedocs/vcs_support/utils.py
Labels: PR: ready for review

#3933 Resync webhooks from Admin
  readthedocs/oauth/services/bitbucket.py
  readthedocs/oauth/services/github.py
  readthedocs/oauth/services/gitlab.py
Labels: PR: ready for review

#3937 Allow extend Translation and Subproject form logic from corporate
  readthedocs/projects/forms.py
Labels: PR: ready for review

#3935 Resync valid webhook for project manually imported
  readthedocs/oauth/utils.py
Labels: PR: ready for review

#3944 Fixed footer ad width fix
  media/css/readthedocs-doc-embed.css
Labels: PR: ready for review

#3948 Make adjustments to Projects page
  media/css/core.css
  readthedocs/templates/core/project_details.html
Labels: Enhancement

#3947 Small change to Chinese language names
  readthedocs/settings/base.py
Labels: PR: ready for review

#3847 Update quickstart from README
  README.rst
Labels: PR: ready for review

#3869 templates: mark a few more strings for translations
  readthedocs/templates/projects/integration_webhook_detail.html
  readthedocs/templates/projects/onboard_detail.html
  readthedocs/templates/projects/onboard_import.html
  readthedocs/templates/projects/project_dashboard_base.html
  readthedocs/templates/projects/project_users.html
Labels: PR: ready for review

#3671 Documentation for build notifications using webhooks.
  docs/guides/build-notifications.rst
Labels: PR: ready for review

#3604 [#2967] Scheduled tasks for cleaning up messages
  readthedocs/core/tasks.py
  readthedocs/core/utils/__init__.py
  readthedocs/settings/base.py
Labels: PR: ready for review

#3959 Remove django-celery-beat and use the default scheduler
  readthedocs/settings/base.py
  requirements/pip.txt
Labels: PR: ready for review

#3800 [RDY] Fix requirements file lookup
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: PR: ready for review

#3899 Fixup DJANGO_SETTINGS_SKIP_LOCAL in tests
  readthedocs/settings/test.py
Labels: PR: ready for review

#3593 Show URLS for exact redirect
  readthedocs/redirects/models.py
  readthedocs/templates/projects/project_redirects.html
Labels: Enhancement, PR: ready for review

#3461 Document creation of slumber user
  docs/install.rst
Labels: PR: ready for review

#3958 Fix some tests with postgres
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_notifications.py
Labels: PR: ready for review

#3955 Add advertising details docs
  docs/advertising-details.rst
  docs/ethical-advertising.rst
  docs/index.rst
  media/javascript/readthedocs-analytics.js
Labels: PR: ready for review

#3536 Doc builder template should check for mkdocs_page_input_path before using it
  readthedocs/doc_builder/templates/doc_builder/data.js.tmpl
Labels: PR: ready for review

#3920 Correctly report mkdocs theme name
  readthedocs/doc_builder/backends/mkdocs.py
Labels: PR: ready for review

#3962 Make `resolve_domain` work when a project is subproject of itself
  readthedocs/core/resolver.py
  readthedocs/rtd_tests/tests/test_resolver.py
Labels: PR: ready for review

#3953 Use pur to upgrade python packages
  requirements/pip.txt
Labels: PR: ready for review

#3946 Don't share state in build task
  readthedocs/projects/tasks.py
  readthedocs/rtd_tests/tests/test_builds.py
  readthedocs/rtd_tests/tests/test_celery.py
Labels: PR: ready for review

#3967 Use latest setuptools (39.0.1) by default on build process
  readthedocs/doc_builder/python_environments.py
Labels: PR: ready for review

#3965 Fix exact redirects.
  readthedocs/redirects/models.py
  readthedocs/rtd_tests/tests/test_redirects.py
Labels: PR: hotfix

#3882 Fix view docs link
  readthedocs/builds/static-src/builds/js/detail.js
  readthedocs/restapi/serializers.py
  readthedocs/templates/builds/build_detail.html
Labels: PR: ready for review

#3975 Fix server_error_500 path on single version
  readthedocs/core/urls/single_version.py
  readthedocs/projects/tasks.py
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: PR: ready for review

#3981 Resolve domain when a project is a translation of itself
  readthedocs/core/resolver.py
  readthedocs/rtd_tests/tests/test_resolver.py
Labels: Bug

#3983 Give TaskStep class knowledge of the underlying task
  readthedocs/projects/tasks.py
Labels: Bug

#4003 Downgrade docker to 3.1.3
  requirements/pip.txt
Labels: PR: ready for review

#4016 Don't check order on assertQuerysetEqual on tests for subprojects
  readthedocs/rtd_tests/tests/test_subprojects.py
Labels: PR: ready for review

#4014 Tests for view docs api response
  readthedocs/rtd_tests/tests/test_api.py
Labels: PR: ready for review

#3982 Remove typekit fonts
  docs/design.rst
  media/css/core.css
  readthedocs/builds/static/builds/css/detail.css
  readthedocs/core/static/core/font/lato/lato-bold.woff
  readthedocs/core/static/core/font/lato/lato-bold.woff2
  readthedocs/core/static/core/font/lato/lato-italic.woff
  readthedocs/core/static/core/font/lato/lato-italic.woff2
  readthedocs/core/static/core/font/lato/lato-regular.woff
  readthedocs/core/static/core/font/lato/lato-regular.woff2
  readthedocs/templates/base.html
Labels: Design, Enhancement, Needed: design decision

#4022 Support sign in and sign up with GH/GL/BB
  media/css/core.css
  readthedocs/settings/base.py
  readthedocs/templates/account/login.html
  readthedocs/templates/account/signup.html
  readthedocs/templates/socialaccount/snippets/provider_list.html
Labels: Enhancement

#3802 [WIP] Remove comments app
  readthedocs/comments/__init__.py
  readthedocs/comments/admin.py
  readthedocs/comments/backend.py
  readthedocs/comments/migrations/0001_initial.py
  readthedocs/comments/migrations/__init__.py
  readthedocs/comments/models.py
  readthedocs/comments/session.py
  readthedocs/comments/static/_static/ajax-loader.gif
  readthedocs/comments/static/_static/comment-bright.png
  readthedocs/comments/static/_static/comment-close.png
  readthedocs/comments/static/_static/comment.png
  readthedocs/comments/static/_static/down-pressed.png
  readthedocs/comments/static/_static/down.png
  readthedocs/comments/static/_static/file.png
  readthedocs/comments/static/_static/minus.png
  readthedocs/comments/static/_static/plus.png
  readthedocs/comments/static/_static/up-pressed.png
  readthedocs/comments/static/_static/up.png
  readthedocs/comments/templates/base.html
  readthedocs/comments/templates/doc.html
  readthedocs/comments/templates/docbase.html
  readthedocs/comments/tests.py
  readthedocs/comments/urls.py
  readthedocs/comments/views.py
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/projects/admin.py
  readthedocs/projects/forms.py
  readthedocs/projects/models.py
  readthedocs/projects/urls/private.py
  readthedocs/projects/views/private.py
  readthedocs/restapi/urls.py
  readthedocs/rtd_tests/tests/test_builds.py
  readthedocs/rtd_tests/tests/test_comments.py
  readthedocs/rtd_tests/tests/test_privacy_urls.py
  readthedocs/rtd_tests/tests/test_views.py
  readthedocs/settings/base.py
  readthedocs/templates/core/project_bar_base.html
  readthedocs/templates/projects/project_comments_moderation.html
  readthedocs/templates/projects/project_comments_settings.html
  readthedocs/templates/projects/project_edit_base.html
  readthedocs/urls.py
Labels: PR: work in progress

#4038 Remove dead code from api v1
  readthedocs/api/base.py
Labels: PR: ready for review

#4035 Bump sphinx default version to 1.7.4
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_building.py
  requirements/pip.txt
Labels: Enhancement, PR: ready for review
