Repository readthedocs/readthedocs.org, pull requests merged in 2018-10, with the labels that each got.

#4727 Fix get_vcs_repo by moving it to the Mixin
  readthedocs/projects/tasks.py
Labels: PR: hotfix

#4747 Use Docker time limit for max lock age
  readthedocs/projects/models.py
  readthedocs/projects/tasks.py
Labels: Accepted, Bug

#4731 Remove /cname endpoint
  readthedocs/core/utils/__init__.py
  readthedocs/restapi/urls.py
  readthedocs/restapi/views/core_views.py
Labels: PR: work in progress

#4605 Run coverage on travis
  .codecov.yml
  .coveragerc
  requirements/testing.txt
  tox.ini
Labels: Improvement

#4382 static: use modern getJSON callbacks
  readthedocs/core/static-src/core/js/doc-embed/search.js
  readthedocs/core/static-src/core/js/tasks.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/projects/static-src/projects/js/import.js
  readthedocs/projects/static/projects/js/import.js
Labels: Improvement

#4438 search: mark more strings for translation
  readthedocs/templates/search/elastic_search.html
Labels: Status: blocked

#3631 Improve installation guide
  docs/.rstcheck.cfg
  docs/conf.py
  docs/install.rst
  requirements/pip.txt
Labels: PR: work in progress
