Repository readthedocs/readthedocs.org, pull requests merged in 2018-02, with the labels that each got.

#3607 Update GSOC
  docs/gsoc.rst
Labels: PR: ready for review

#3559 Use DRF 3.1 `pagination_class`
  .pre-commit-config.yaml
  readthedocs/restapi/utils.py
  readthedocs/restapi/views/model_views.py
  readthedocs/rtd_tests/tests/test_api.py
Labels: PR: ready for review

#3556 Mount `pip_cache_path` in Docker container
  readthedocs/doc_builder/environments.py
  readthedocs/projects/models.py
Labels: Enhancement, PR: ready for review

#3571 Don't allow to create a subproject of a project itself
  readthedocs/projects/forms.py
  readthedocs/rtd_tests/tests/test_subprojects.py
Labels: PR: ready for review

#3520 Log `git checkout` and expose to users
  docs/builds.rst
  readthedocs/core/management/commands/pull.py
  readthedocs/core/views/hooks.py
  readthedocs/doc_builder/environments.py
  readthedocs/projects/apps.py
  readthedocs/projects/models.py
  readthedocs/projects/tasks.py
  readthedocs/rtd_tests/tests/test_builds.py
  readthedocs/rtd_tests/tests/test_celery.py
  readthedocs/rtd_tests/tests/test_doc_building.py
  readthedocs/vcs_support/backends/bzr.py
  readthedocs/vcs_support/backends/git.py
  readthedocs/vcs_support/backends/hg.py
  readthedocs/vcs_support/backends/svn.py
  readthedocs/vcs_support/base.py
Labels: PR: ready for review

#3621 Update the operations team
  AUTHORS.rst
Labels: PR: ready for review

#3498 Update docs
  docs/builds.rst
  docs/docs.rst
  docs/faq.rst
  docs/install.rst
Labels: PR: ready for review

#3638 Fix SVN initialization for command logging
  readthedocs/vcs_support/backends/svn.py
Labels: PR: ready for review

#3641 Update RTD security docs
  docs/index.rst
  docs/security.rst
  readthedocs/templates/security.html
  readthedocs/templates/security.txt
  readthedocs/urls.py
Labels: PR: ready for review

#3623 Ability to override the creation of the Celery App
  readthedocs/settings/base.py
  readthedocs/worker.py
  tox.ini
Labels: PR: ready for review

#3653 Send proper context to celery email notification task
  readthedocs/projects/tasks.py
Labels: PR: ready for review

#3656 Fix issue with missing setting in oauth SyncRepo task
  readthedocs/settings/base.py
Labels: PR: ready for review

#3657 Hotfix for adding logging call back into project sync task
  readthedocs/projects/tasks.py
Labels: PR: hotfix, PR: ready for review

#3661 Check for submodules
  readthedocs/rtd_tests/tests/test_backend.py
  readthedocs/rtd_tests/utils.py
  readthedocs/vcs_support/backends/git.py
Labels: PR: ready for review
