Repository readthedocs/readthedocs.org, pull requests merged in 2018-08, with the labels that each got.

#4489 All static media is run through "collectstatic"
  .gitignore
  media/font/fontawesome_webfont.woff2
  media/fonts
  readthedocs/settings/base.py
  readthedocs/templates/admin.html
  readthedocs/templates/base.html
  readthedocs/templates/builds/build_list.html
  readthedocs/urls.py
Labels: PR: work in progress

#4517 Undo static rewrites of URL’s
  readthedocs/templates/base.html
  readthedocs/templates/builds/build_list.html
Labels: PR: hotfix

#4426 Replace old mimeparse package with python-mimeparse
  requirements/pip.txt
Labels: Improvement

#4531 Remove mailgun from our dependencies
  requirements/deploy.txt
Labels: Accepted, Bug

#4542 Remove hiredis
  requirements/deploy.txt
Labels: PR: hotfix
