Repository readthedocs/readthedocs.org, pull requests merged in 2018-11, with the labels that each got.

#4569 Issue #4551 Changed mock docks to use sphinx
  docs/faq.rst
Labels: PR: work in progress

#4842 Version compare warning text
  readthedocs/core/static-src/core/js/doc-embed/version-compare.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/projects/static/projects/js/tools.js
  readthedocs/static/vendor/jquery-migrate-standalone.js
  readthedocs/static/vendor/jquery-migrate.js
  readthedocs/static/vendor/jquery-standalone.js
  readthedocs/static/vendor/jquery-ui-standalone.js
  readthedocs/static/vendor/jquery-ui.js
  readthedocs/static/vendor/jquery.js
  readthedocs/static/vendor/knockout.js
  readthedocs/static/vendor/underscore-standalone.js
  readthedocs/static/vendor/underscore.js
Labels: Needed: design decision

#4834 Show the project's slug in the dashboard
  readthedocs/templates/core/project_detail_right.html
Labels: Needed: design decision

#3759 New languages
  readthedocs/projects/constants.py
  readthedocs/projects/migrations/0029_add_additional_languages.py
Labels: PR: work in progress

#3464 Make slug field a valid DNS label
  readthedocs/projects/migrations/0030_change-max-length-project-slug.py
  readthedocs/projects/models.py
Labels: Needed: design decision, PR: work in progress

#4622 Redirect to build detail post manual build
  readthedocs/builds/views.py
  readthedocs/core/utils/__init__.py
  readthedocs/projects/views/private.py
  readthedocs/rtd_tests/tests/test_views.py
Labels: Needed: tests

#4545 Enable timezone support and set timezone to UTC
  readthedocs/core/admin.py
  readthedocs/core/fixtures/eric.json
  readthedocs/core/management/commands/clean_builds.py
  readthedocs/oauth/services/base.py
  readthedocs/projects/fixtures/test_auth.json
  readthedocs/projects/fixtures/test_data.json
  readthedocs/projects/tasks.py
  readthedocs/projects/views/base.py
  readthedocs/rtd_tests/tests/test_project.py
  readthedocs/rtd_tests/tests/test_project_views.py
  readthedocs/search/indexes.py
  readthedocs/settings/base.py
Labels: PR: work in progress

#4804 Appropiate logging when a LockTimeout for VCS is reached
  readthedocs/projects/tasks.py
Labels: PR: work in progress
