Repository readthedocs/readthedocs.org, pull requests merged in 2018-05, with the labels that each got.

#4039 Remove haystack from code base
  readthedocs/api/base.py
  readthedocs/api/utils.py
  readthedocs/core/forms.py
  readthedocs/projects/search_indexes.py
  readthedocs/settings/base.py
  readthedocs/settings/dev.py
  readthedocs/settings/test.py
  readthedocs/templates/projects/project_analytics.html
  readthedocs/templates/projects/project_embed.html
  readthedocs/templates/projects/project_version_list.html
  readthedocs/templates/search/base_facet.html
  readthedocs/templates/search/base_search.html
  readthedocs/templates/search/elastic_project_search.html
  readthedocs/templates/search/elastic_search.html
  readthedocs/templates/search/faceted_author.html
  readthedocs/templates/search/faceted_results.html
  readthedocs/templates/search/search.html
  requirements/pip.txt
Labels: PR: ready for review

#4044 Fix unbalanced div
  readthedocs/templates/search/elastic_project_search.html
Labels: PR: ready for review

#4049 Fix woff2 font files
  .gitattributes
  readthedocs/core/static/core/font/lato/lato-bold.woff2
  readthedocs/core/static/core/font/lato/lato-italic.woff2
  readthedocs/core/static/core/font/lato/lato-regular.woff2
Labels: PR: ready for review

#3934 Allow import Gitlab repo manually and set a webhook automatically
  readthedocs/oauth/services/gitlab.py
  readthedocs/rtd_tests/tests/test_oauth.py
Labels: PR: ready for review

#3878 Design docs for the yaml file
  docs/design/yaml-file.rst
Labels: PR: ready for review

#3725 Fixes #2953 - Url resolved with special characters
  readthedocs/profiles/urls/public.py
  readthedocs/rtd_tests/tests/test_urls.py
Labels: PR: ready for review

#4083 Use next field to redirect user when login is done by social
  readthedocs/templates/account/login.html
Labels: PR: ready for review

#3922 Enable ads on the readthedocs mkdocs theme
  readthedocs/core/static-src/core/js/doc-embed/constants.js
  readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
  readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
Labels: PR: ready for review

#4080 Update the `documentation_type` when it's set to 'auto'
  readthedocs/projects/tasks.py
Labels: PR: ready for review

#4112 Remove Django deprecation warning
  readthedocs/settings/base.py
Labels: PR: ready for review

#4105 Set valid clone in project instance inside the version object also
  readthedocs/projects/tasks.py
Labels: PR: ready for review

#4120 Don't sync _static dir for search builder
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/base.py
  readthedocs/rtd_tests/tests/test_doc_builder.py
Labels: PR: ready for review

#3790 Additional validation when changing the project language
  readthedocs/projects/forms.py
  readthedocs/rtd_tests/tests/test_project.py
  readthedocs/rtd_tests/tests/test_project_forms.py
Labels: PR: ready for review

#3685 Improve yaml config docs
  docs/yaml-config.rst
Labels: PR: ready for review

#4060 Fix missing fonts
  gulpfile.js
  readthedocs/core/static/core/font/Lato-Italic.ttf
  readthedocs/core/static/core/font/fontawesome-webfont.woff2
Labels: Design

#3624 Add rstcheck to CI
  .travis.yml
  docs/.rstcheck.cfg
  docs/automatic-redirects.rst
  docs/business/index.rst
  docs/canonical.rst
  docs/changelog.rst
  docs/contribute.rst
  docs/custom_installs/local_rtd_vm.rst
  docs/design.rst
  docs/design/theme-context.rst
  docs/dmca/index.rst
  docs/faq.rst
  docs/getting_started.rst
  docs/guides/build-notifications.rst
  docs/i18n.rst
  docs/index.rst
  docs/localization.rst
  docs/sponsors.rst
  docs/webhooks.rst
  requirements/docs-lint.txt
  tox.ini
Labels: PR: ready for review

#4054 Put the rtd extension to the beginning of the list
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Labels: PR: ready for review

#4133 oauth/services: don't abuse log.exception
  readthedocs/oauth/services/bitbucket.py
  readthedocs/oauth/services/github.py
  readthedocs/oauth/services/gitlab.py
Labels: PR: ready for review

#4134 oauth/services: correct error handling in paginate
  readthedocs/oauth/services/base.py
Labels: PR: ready for review

#4107 Add `has_valid_clone` and `has_valid_webhook` to ProjectAdminSerializer
  readthedocs/restapi/serializers.py
  readthedocs/rtd_tests/tests/test_api.py
Labels: PR: ready for review

#4114 Use quiet mode to retrieve branches from mercurial
  readthedocs/vcs_support/backends/hg.py
Labels: PR: ready for review

#3703 Ticket #3694: rename owners to maintainers
  readthedocs/templates/core/project_detail_right.html
Labels: PR: ready for review

#3677 Refactor to replace old logging to avoid mangling
  readthedocs/core/symlink.py
Labels: PR: ready for review

#3615 Update Git on prod
  docs/install.rst
Labels: PR: ready for review

#3595 Allow to hide version warning
  docs/versions.rst
  readthedocs/builds/static/builds/js/detail.js
  readthedocs/core/static-src/core/js/doc-embed/footer.js
  readthedocs/core/static/core/js/autocomplete.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/core/static/core/js/site.js
  readthedocs/gold/static/gold/js/gold.js
  readthedocs/projects/forms.py
  readthedocs/projects/migrations/0024_add-show-version-warning.py
  readthedocs/projects/migrations/0025_show-version-warning-existing-projects.py
  readthedocs/projects/models.py
  readthedocs/projects/static/projects/js/import.js
  readthedocs/projects/static/projects/js/tools.js
  readthedocs/restapi/views/footer_views.py
  readthedocs/rtd_tests/tests/test_footer.py
Labels: PR: ready for review

#3514 Modernize Python 2 code to get ready for Python 3
  deploy/delete_stale_projects.py
  deploy/flask-redirects.py
  deploy/nginx-smoke-test.py
Labels: Enhancement, Needed: more information

#3504 Consistent version format
  readthedocs/core/static-src/core/js/doc-embed/version-compare.js
  readthedocs/restapi/views/footer_views.py
  readthedocs/rtd_tests/tests/test_footer.py
Labels: PR: ready for review

#4052 Use gitpython for tags
  readthedocs/rtd_tests/tests/test_backend.py
  readthedocs/rtd_tests/utils.py
  readthedocs/vcs_support/backends/git.py
  tox.ini
Labels: PR: ready for review

#3764 [RDY] Fix tests for environment
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: PR: ready for review

#4146 Use autosectionlabel extension
  docs/conf.py
  docs/contribute.rst
  docs/design.rst
  docs/ethical-advertising.rst
  docs/faq.rst
  docs/getting_started.rst
  docs/install.rst
  docs/issue-labels.rst
  docs/privacy-policy.rst
  docs/security.rst
  docs/webhooks.rst
Labels: PR: work in progress

#4150 Small footer rework
  media/css/core.css
  readthedocs/rtd_tests/tests/test_project.py
  readthedocs/templates/base.html
Labels: Design

#3512 Remove outline reset to bring back outline
  media/css/core.css
Labels: Enhancement, PR: ready for review

#3585 Download raw build log
  readthedocs/restapi/serializers.py
  readthedocs/restapi/templates/restapi/log.txt
  readthedocs/restapi/views/model_views.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/templates/builds/build_detail.html
Labels: Enhancement, PR: ready for review

#4172 Fix some warnings on docs
  docs/api/projects.rst
  docs/privacy-policy.rst
  docs/team.rst
  readthedocs/builds/managers.py
  readthedocs/builds/models.py
  readthedocs/core/utils/extend.py
  readthedocs/core/views/hooks.py
  readthedocs/doc_builder/environments.py
  readthedocs/projects/models.py
  readthedocs/projects/views/mixins.py
  readthedocs/rtd_tests/tests/test_project_symlinks.py
Labels: PR: ready for review

#4173 Use anonymous refs in CHANGELOG
  CHANGELOG.rst
Labels: PR: ready for review

#4169 Note about state and metro ad targeting
  docs/advertising-details.rst
Labels: PR: ready for review

#4176 Fix issues with search javascript
  readthedocs/core/static-src/core/js/doc-embed/search.js
Labels: Bug
