Repository readthedocs/readthedocs.org, pull requests merged in 2018-06, with the labels that each got.

#4116 Test for search functionality
  .travis.yml
  conftest.py
  docs/tests.rst
  readthedocs/core/management/commands/reindex_elasticsearch.py
  readthedocs/search/indexes.py
  readthedocs/search/tests/__init__.py
  readthedocs/search/tests/conftest.py
  readthedocs/search/tests/data/docs/story.json
  readthedocs/search/tests/data/docs/wiping.json
  readthedocs/search/tests/data/kuma/docker.json
  readthedocs/search/tests/data/kuma/documentation.json
  readthedocs/search/tests/data/pipeline/installation.json
  readthedocs/search/tests/data/pipeline/signals.json
  readthedocs/search/tests/dummy_data.py
  readthedocs/search/tests/test_views.py
  readthedocs/search/tests/utils.py
  readthedocs/settings/dev.py
  readthedocs/templates/search/elastic_search.html
  requirements/testing.txt
  scripts/travis/install_elasticsearch.sh
  scripts/travis/run_tests.sh
Labels: PR: ready for review

#3966 tests: fixup url tests in test_privacy_urls
  readthedocs/rtd_tests/tests/test_privacy_urls.py
Labels: PR: ready for review

#3445 Wrap versions' list to look more consistent
  readthedocs/templates/core/project_details.html
  readthedocs/templates/core/project_downloads.html
  readthedocs/templates/projects/integration_list.html
  readthedocs/templates/projects/project_version_list.html
Labels: Design, PR: ready for review

#4131 Server side analytics
  readthedocs/analytics/__init__.py
  readthedocs/analytics/apps.py
  readthedocs/analytics/tasks.py
  readthedocs/analytics/tests.py
  readthedocs/analytics/utils.py
  readthedocs/analytics/vendor/__init__.py
  readthedocs/analytics/vendor/ipaddress.py
  readthedocs/settings/base.py
  requirements/pip.txt
Labels: PR: ready for review

#4124 Upgrade packages with pur
  requirements/pip.txt
Labels: PR: ready for review

#3805 #3779: Remove autocomplete js from templates
  media/javascript/instantsearch.js
  readthedocs/core/static-src/core/js/autocomplete.js
  readthedocs/core/static/core/js/autocomplete.js
  readthedocs/gold/templates/gold/projects.html
  readthedocs/projects/urls/public.py
  readthedocs/projects/views/public.py
  readthedocs/templates/base.html
  readthedocs/templates/core/widesearchbar.html
  readthedocs/templates/search/elastic_project_search.html
Labels: PR: ready for review

#3646 Add get in touch section
  README.rst
  docs/contribute.rst
Labels: PR: work in progress

#4207 Allow staff to trigger project builds
  readthedocs/builds/views.py
Labels: PR: ready for review

#4078 Handle raising exceptions from PublicTask
  readthedocs/core/utils/tasks/public.py
  readthedocs/restapi/views/task_views.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_celery.py
Labels: PR: ready for review

#4180 Updates to our triage guidelines
  docs/issue-labels.rst
Labels: Needed: design decision

#3546 Allow tags from GitHub webhooks
  readthedocs/projects/models.py
  readthedocs/restapi/views/integrations.py
  readthedocs/rtd_tests/tests/test_api.py
Labels: Improvement

#4113 Fix resync remote repos
  readthedocs/builds/static/builds/js/detail.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/core/static/core/js/site.js
  readthedocs/gold/static/gold/js/gold.js
  readthedocs/projects/static-src/projects/js/import.js
  readthedocs/projects/static/projects/js/import.js
  readthedocs/projects/static/projects/js/tools.js
Labels: Bug

#4225 Move parser tests from rtd-build repo
  readthedocs/config/__init__.py
  readthedocs/config/find.py
  readthedocs/config/parser.py
  readthedocs/config/tests/__init__.py
  readthedocs/config/tests/fixtures/bad_encode_project/schaue pülaylist an.py
  readthedocs/config/tests/test_find.py
  readthedocs/config/tests/test_parser.py
  readthedocs/config/tests/test_utils.py
  readthedocs/config/tests/utils.py
Labels: PR: work in progress

#4241 Downgrade docker to 3.1.3 because of timeouts in EXEC call
  requirements/pip.txt
Labels: PR: hotfix

#4228 projects: serve badge with same protocol as site
  readthedocs/projects/views/public.py
Labels: Needed: tests

#4261 Revert "Merge pull request #4206 from FlorianKuckelkorn/fix/pip-breaking-change"
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: PR: hotfix

#4242 Move config module from rtd-build repo
  readthedocs/config/tests/test_validation.py
  readthedocs/config/validation.py
  readthedocs/rtd_tests/tests/test_build_config.py
  requirements/testing.txt
Labels: PR: work in progress

#4236 Allow staying logged in for longer
  readthedocs/settings/base.py
  readthedocs/templates/profiles/private/advertising_profile.html
Labels: Improvement, Needed: design decision
