Repository readthedocs/readthedocs.org, pull requests merged in 2018-09, with the labels that each got.

#4597 Fixes an issue with duplicate gold subscriptions
  readthedocs/gold/forms.py
Labels: Bug

#4547 Docs for hidding "On ..." section from versions menu
  docs/guides/remove-edit-buttons.rst
Labels: Needed: documentation

#3912 Use str to get the exception message
  readthedocs/restapi/views/model_views.py
Labels: PR: work in progress

#4611 Add cwd to subprocess calls
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_building.py
Labels: Improvement

#4467 [Fix #4268] Adding Documentation for upgraded Search
  docs/custom_installs/elasticsearch.rst
  docs/development/search.rst
  docs/index.rst
  docs/install.rst
  readthedocs/core/management/commands/provision_elasticsearch.py
Labels: PR: work in progress

#4556 Updates and simplification for mkdocs
  media/css/readthedocs-doc-embed.css
  readthedocs/core/static-src/core/js/doc-embed/footer.js
  readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
  readthedocs/core/static-src/core/js/doc-embed/sphinx.js
  readthedocs/doc_builder/backends/mkdocs.py
  readthedocs/doc_builder/base.py
  readthedocs/rtd_tests/tests/test_doc_builder.py
  readthedocs/templates/mkdocs/readthedocs/searchbox.html
  readthedocs/templates/mkdocs/readthedocs/versions.html
Labels: Needed: design decision

#4655 Put search step back into project build task
  readthedocs/projects/tasks.py
Labels: PR: hotfix

#4683 Fix the queryset used in chunking
  readthedocs/search/parse_json.py
  readthedocs/search/tasks.py
Labels: PR: hotfix

#4685 Fix bug where we were not indexing Sphinx HTMLDir projects
  readthedocs/search/documents.py
  readthedocs/search/management/commands/reindex_elasticsearch.py
Labels: PR: hotfix
