Repository readthedocs/readthedocs.org, pull requests merged in 2019-11, with the labels that each got.

#6131 Use different setting for footer api url
  readthedocs/core/static-src/core/js/doc-embed/footer.js
  readthedocs/core/static-src/core/js/doc-embed/rtd-data.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
  readthedocs/doc_builder/backends/mkdocs.py
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
  readthedocs/projects/static/projects/js/tools.js
  readthedocs/settings/base.py
Labels: Needed: design decision

#6163 Protection against ReDoS
  readthedocs/builds/models.py
  requirements/pip.txt
Labels: Accepted

#5996 Implement UI for automation rules
  gulpfile.js
  media/css/core.css
  readthedocs/builds/constants.py
  readthedocs/builds/forms.py
  readthedocs/builds/managers.py
  readthedocs/builds/migrations/0012_add-predefined-match-arg-field.py
  readthedocs/builds/models.py
  readthedocs/projects/static-src/projects/js/automation-rules.js
  readthedocs/projects/static/projects/js/automation-rules.js
  readthedocs/projects/urls/private.py
  readthedocs/projects/views/private.py
  readthedocs/rtd_tests/tests/test_automation_rule_views.py
  readthedocs/rtd_tests/tests/test_automation_rules.py
  readthedocs/rtd_tests/tests/test_privacy_urls.py
  readthedocs/templates/builds/regexautomationrule_form.html
  readthedocs/templates/builds/versionautomationrule_list.html
  readthedocs/templates/projects/project_edit_base.html
Labels: Accepted

#6380 Fix search indexing
  readthedocs/search/utils.py
Labels: PR: hotfix

#6394 Fix CSS and how we were handling html in automation rule UI
  media/css/core.css
  readthedocs/projects/static-src/projects/css/admin.less
  readthedocs/projects/static/projects/css/admin.css
  readthedocs/templates/builds/versionautomationrule_list.html
Labels: PR: hotfix
