Repository readthedocs/readthedocs.org, pull requests merged in 2019-06, with the labels that each got.

#5760 Try to fix Elastic connection pooling issues
  readthedocs/search/documents.py
  readthedocs/search/faceted_search.py
  readthedocs/search/tasks.py
Labels: PR: hotfix, PR: work in progress

#5763 Try to fix Elastic connection pooling issues
  readthedocs/search/documents.py
  readthedocs/search/faceted_search.py
  readthedocs/search/signals.py
  readthedocs/search/tasks.py
Labels: PR: hotfix

#5635 Use `--upgrade` instead of `--force-reinstall` for pip installs
  readthedocs/doc_builder/python_environments.py
Labels: Needed: more information

#4608 Add a contrib Dockerfile for local build image on Linux
  contrib/Dockerfile
  contrib/docker_build.sh
  contrib/readme.rst
  docs/development/buildenvironments.rst
  readthedocs/settings/dev.py
Labels: Accepted, Improvement

#5828 Auto Build Documentation on Pull Request (PR Builder)
  readthedocs/api/v2/views/integrations.py
  readthedocs/core/views/hooks.py
  readthedocs/projects/constants.py
  readthedocs/projects/tasks.py
  readthedocs/vcs_support/backends/bzr.py
  readthedocs/vcs_support/backends/git.py
  readthedocs/vcs_support/backends/hg.py
  readthedocs/vcs_support/backends/svn.py
Labels: PR: work in progress
