Repository readthedocs/readthedocs.org, pull requests merged in 2019-02, with the labels that each got.

#3581 Set python3 as default interpreter
  docs/config-file/v1.rst
  readthedocs/projects/migrations/0038_change-default-python-interpreter.py
  readthedocs/projects/models.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_config_integration.py
Labels: Accepted

#5130 Allow custom 404.html on projects
  docs/conf.py
  readthedocs/core/views/__init__.py
  readthedocs/core/views/serve.py
  readthedocs/doc_builder/python_environments.py
  readthedocs/rtd_tests/tests/test_doc_serving.py
  requirements/local-docs-build.txt
Labels: Feature

#5243 Be more defensive in our 404 handler
  readthedocs/core/views/__init__.py
Labels: PR: hotfix

#5244 Don't update search on HTMLFile save
  readthedocs/search/signals.py
  readthedocs/search/tests/conftest.py
  readthedocs/search/tests/test_api.py
  readthedocs/search/tests/test_views.py
Labels: PR: hotfix

#5259 Automate docs version from our setup.cfg
  docs/conf.py
Labels: Improvement

#5255 Add admin actions for building versions
  readthedocs/builds/admin.py
  readthedocs/projects/admin.py
Labels: Improvement

#5309 Fix an issue where we were not properly filtering projects
  readthedocs/search/api.py
  readthedocs/search/documents.py
  readthedocs/search/tests/test_api.py
  readthedocs/search/utils.py
Labels: Bug

#5118 Logging exceptions rework
  readthedocs/projects/tasks.py
Labels: Improvement

#4947 Store ePubs and PDFs in media storage
  readthedocs/builds/syncers.py
  readthedocs/projects/models.py
  readthedocs/projects/tasks.py
  readthedocs/projects/views/public.py
  readthedocs/rtd_tests/tests/test_project.py
  readthedocs/rtd_tests/tests/test_project_views.py
  readthedocs/rtd_tests/tests/test_projects_tasks.py
Labels: Accepted

#5281 Tweek css for sphinx_prompt
  docs/_static/css/sphinx_prompt_css.css
Labels: PR: work in progress

#4940 Validate webhook's payload
  .coveragerc
  docs/webhooks.rst
  readthedocs/integrations/migrations/0004_add_integration_secret.py
  readthedocs/integrations/migrations/0005_change_default_integration_secret.py
  readthedocs/integrations/models.py
  readthedocs/integrations/utils.py
  readthedocs/oauth/services/github.py
  readthedocs/oauth/services/gitlab.py
  readthedocs/projects/forms.py
  readthedocs/restapi/views/integrations.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_integrations.py
Labels: Improvement
