Repository readthedocs/readthedocs.org, pull requests merged in 2019-01, with the labels that each got.

#4805 Handle 401, 403 and 404 status codes when hitting GitHub for webhook
  readthedocs/oauth/services/github.py
Labels: PR: work in progress

#4958 Add test case for send_notifications on VersionLockedError
  readthedocs/rtd_tests/tests/test_celery.py
Labels: Needed: more information

#5086 Support custom robots.txt
  docs/faq.rst
  readthedocs/core/urls/subdomain.py
  readthedocs/core/views/serve.py
  readthedocs/rtd_tests/tests/test_doc_serving.py
Labels: Accepted

#4891 Fix the failing domain deletion task
  readthedocs/core/symlink.py
  readthedocs/projects/models.py
  readthedocs/projects/tasks.py
Labels: Bug

#5097 Do not list banned projects under /projects/
  readthedocs/projects/views/public.py
Labels: PR: work in progress

#5056 Use default settings for Config object
  readthedocs/config/config.py
  readthedocs/rtd_tests/tests/test_config_integration.py
  readthedocs/settings/base.py
Labels: Accepted

#5143 Remove logic for guessing slug from an unregistered domain
  readthedocs/core/middleware.py
  readthedocs/core/templates/core/dns-404.html
  readthedocs/core/utils/__init__.py
  readthedocs/rtd_tests/tests/test_middleware.py
  requirements/pip.txt
Labels: Bug, Status: blocked
