Repository readthedocs/readthedocs.org, pull requests merged in 2020-12, with the labels that each got.

#7725 Bitbucket: mainbranch can be None
  readthedocs/oauth/services/bitbucket.py
  readthedocs/rtd_tests/tests/test_oauth.py
Labels: PR: hotfix

#7582 Search: update to ES 7.x
  .circleci/config.yml
  readthedocs/search/faceted_search.py
  requirements/pip.txt
Labels: PR: hotfix, Status: blocked

#7382 Sync versions: create new versions in bulk
  readthedocs/api/v2/utils.py
Labels: Accepted

#7755 Register AutoscaleBuildersTask
  readthedocs/builds/apps.py
Labels: PR: hotfix
