Repository readthedocs/readthedocs.org, pull requests merged in 2020-10, with the labels that each got.

#7541 Downloads: fix translation of a subproject
  readthedocs/projects/models.py
  readthedocs/rtd_tests/tests/test_version.py
Labels: Accepted, Bug, Priority: high

#7506 No longer proxy RTD ads through RTD servers
  media/css/readthedocs-doc-embed.css
  package-lock.json
  package.json
  readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
  readthedocs/core/static-src/core/js/readthedocs-doc-embed.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
Labels: PR: work in progress

#7586 Ads JS hotfix
  readthedocs/core/static-src/core/js/doc-embed/sponsorship.js
  readthedocs/core/static/core/js/readthedocs-doc-embed.js
Labels: PR: hotfix

#7578 Add settings and docker configuration for working with new theme
  dockerfiles/Dockerfile
  readthedocs/settings/base.py
  readthedocs/settings/docker_compose.py
Labels: Improvement

#7579 Undeprecate APIv2 in docs
  docs/api/v2.rst
Labels: Improvement

#7580 Add remoterepo query param
  readthedocs/api/v2/views/model_views.py
Labels: Improvement

#7596 Default to sphinx theme 0.5.0 when defaulting to latest sphinx
  readthedocs/doc_builder/python_environments.py
Labels: Bug
