Repository readthedocs/readthedocs.org, pull requests merged in 2021-01, with the labels that each got.

#7169 Design document for RemoteRepository DB normalization
  docs/development/design/refactor-remote-repository.rst
Labels: Accepted

#7540 Sphinx: use html_baseurl for setting the canonical URL
  docs/guides/canonical.rst
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Labels: Status: blocked

#7820 Log Stripe Resource fallback creation in Stripe
  readthedocs/payments/forms.py
Labels: PR: hotfix

#7845 Fix conf.py for external versions
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Labels: PR: hotfix

#7841 Metric tasks for community
  readthedocs/metrics/__init__.py
  readthedocs/metrics/tasks.py
Labels: PR: hotfix
