Repository readthedocs/readthedocs.org, pull requests merged in 2021-06, with the labels that each got.

#7594 Add APIv3 version edit URL
  docs/api/v3.rst
  readthedocs/api/v3/serializers.py
  readthedocs/api/v3/tests/responses/projects-detail.json
  readthedocs/api/v3/tests/responses/projects-versions-builds-list_POST.json
  readthedocs/api/v3/tests/responses/projects-versions-detail.json
Labels: Accepted, Improvement

#8142 Add project/build filters
  readthedocs/builds/filters.py
  readthedocs/builds/views.py
  readthedocs/projects/filters.py
  readthedocs/projects/views/private.py
  readthedocs/projects/views/public.py
Labels: Status: blocked

#6381 Add tests for remove index files
  readthedocs/search/tests/conftest.py
  readthedocs/search/tests/test_api.py
  readthedocs/search/tests/test_faceted_search.py
  readthedocs/search/tests/test_utils.py
  readthedocs/search/tests/test_xss.py
Labels: Needed: design decision
