Repository readthedocs/readthedocs.org, pull requests merged in 2022-08, with the labels that each got.

#9404 Fix missing indentation on reStructuredText badge code
  readthedocs/templates/core/badge_markup.html
Labels: Bug

#9482 Sphinx domain: change type of ID field
  readthedocs/sphinx_domains/apps.py
  readthedocs/sphinx_domains/migrations/0007_alter_sphinxdomain_id.py
Labels: Status: blocked

#9496 Custom urlconf: support serving static files
  readthedocs/projects/models.py
  readthedocs/proxito/tests/test_middleware.py
Labels: PR: hotfix

#9537 Dependencies: pin deploy dependencies
  requirements/deploy.in
  requirements/deploy.txt
Labels: PR: hotfix

#9560 Templates: minor typo
  readthedocs/domains/templates/domains/notifications/pending_domain_configuration_site.html
Labels: PR: hotfix

#9564 Embed API: fix CORS check
  readthedocs/core/signals.py
  readthedocs/rtd_tests/tests/test_middleware.py
Labels: PR: hotfix
