Repository readthedocs/readthedocs.org, pull requests merged in 2022-10, with the labels that each got.

#9622 Docs: Re-scope Intersphinx article as a how-to
  docs/user/guides/authors.rst
  docs/user/guides/intersphinx.rst
Labels: Improvement

#9656 Adds more basic info to the default 404 page
  readthedocs/templates/404.html
Labels: Design

#9660 Docs: Use current year instead of hard-coded 2010
  docs/conf.py
Labels: Improvement

#9672 Run `blacken-docs` precommit hook on all files
  docs/dev/design/better-doc-urls-handling.rst
  docs/dev/design/theme-context.rst
  docs/dev/install.rst
  docs/user/advertising/ad-customization.rst
  docs/user/config-file/v1.rst
  docs/user/environment-variables.rst
  docs/user/guides/cross-referencing-with-sphinx.rst
  docs/user/guides/intersphinx.rst
  docs/user/guides/jupyter.rst
  docs/user/guides/pdf-non-ascii-languages.rst
  docs/user/intro/getting-started-with-sphinx.rst
Labels: hacktoberfest-accepted
