Repository readthedocs/readthedocs.org, pull requests merged in 2022-12, with the labels that each got.

#9784 Docs: Move "Choosing between our two platforms" to Explanation (Diátaxis)
  docs/user/index.rst
Labels: Improvement, Needed: documentation

#9676 Docs: Split Custom Domains as Explanation and How-to Guide (Diátaxis)
  docs/conf.py
  docs/user/canonical-urls.rst
  docs/user/custom-domains.rst
  docs/user/glossary.rst
  docs/user/guides/administrators.rst
  docs/user/guides/canonical-urls.rst
  docs/user/guides/custom-domains.rst
  docs/user/hosting.rst
  docs/user/img/mermaid-custom-domains.png
  docs/user/img/mermaid-custom-domains.svg
  docs/user/index.rst
  requirements/docs.in
  requirements/docs.txt
Labels: Improvement

#9679 Docs: Split up Pull Request Builds into a how-to guide and reference (Diátaxis)
  docs/user/guides/administrators.rst
  docs/user/guides/pull-requests.rst
  docs/user/index.rst
  docs/user/pull-requests.rst
Labels: Improvement

#9788 Do not build documentation in Circle CI, Read the Docs handles that :100:
  .circleci/config.yml
  .readthedocs.yml
  tox.ini
Labels: Improvement

#9790 Docs: Relabel Localization as Explanation (Diátaxis)
  docs/user/index.rst
  docs/user/localization.rst
Labels: Improvement

#9675 Docs: Split and relabel VCS integration as explanation and how-to (Diátaxis)
  docs/_static/js/expand_tabs.js
  docs/user/guides/administrators.rst
  docs/user/guides/git-integrations.rst
  docs/user/index.rst
  docs/user/integrations.rst
Labels: Improvement

#9801 Docs: Split SSO docs into HowTo/Explanation
  CHANGELOG.rst
  docs/conf.py
  docs/dev/install.rst
  docs/user/_includes/organization-permissions.rst
  docs/user/api/v3.rst
  docs/user/commercial/single-sign-on.rst
  docs/user/connected-accounts.rst
  docs/user/features.rst
  docs/user/guides/administrators.rst
  docs/user/guides/manage-read-the-docs-teams.rst
  docs/user/guides/pull-requests.rst
  docs/user/guides/setup-single-sign-on-github-gitlab-bitbucket.rst
  docs/user/guides/setup-single-sign-on-google-email.rst
  docs/user/index.rst
  docs/user/shared/admonition-rtd-business.rst
  readthedocs/api/v2/views/integrations.py
  readthedocs/builds/models.py
  readthedocs/builds/tasks.py
  readthedocs/builds/utils.py
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/oauth/services/bitbucket.py
  readthedocs/projects/models.py
  readthedocs/templates/homepage.html
Labels: Improvement

#9832 Docs: Relabel the "Science" page as Explanation
  docs/user/index.rst
  docs/user/science.rst
Labels: Improvement, Needed: documentation

#9835 Docs: Relabel "Single version documentation" documentation from feature to explanation (Diátaxis)
  docs/user/index.rst
  docs/user/single_version.rst
Labels: Improvement, Needed: documentation

#9837 Invitations: fix model name (object_type)
  readthedocs/invitations/models.py
Labels: Bug

#9785 Docs: Split Subprojects in Explanation and How-to (Diátaxis)
  docs/user/guides/administrators.rst
  docs/user/guides/intersphinx.rst
  docs/user/guides/subprojects.rst
  docs/user/img/screenshot_subprojects_list.png
  docs/user/index.rst
  docs/user/subprojects.rst
Labels: Improvement, Needed: documentation

#9677 Docs: Split Traffic Analytics to a How-to guide and a Feature entry (Diátaxis)
  docs/user/_static/images/search-analytics-demo.png
  docs/user/analytics.rst
  docs/user/guides/administrators.rst
  docs/user/guides/authors.rst
  docs/user/guides/developers.rst
  docs/user/guides/search-analytics.rst
  docs/user/index.rst
  docs/user/reference/analytics.rst
  docs/user/reference/features.rst
  docs/user/server-side-search/index.rst
Labels: Improvement
