Repository readthedocs/readthedocs.org, pull requests merged in 2023-03, with the labels that each got.

#10090 Fix intersphinx references to myst-parser (updated in myst-parser 0.19)
  docs/user/guides/cross-referencing-with-sphinx.rst
  docs/user/guides/jupyter.rst
  docs/user/guides/migrate-rest-myst.md
Labels: Needed: documentation, Bug

#10091 Docs: Update documentation for search.ignore
  docs/user/config-file/v2.rst
Labels: Improvement, Needed: documentation

#10093 Docs: Move a reference and remove an empty paranthesis
  docs/user/user-defined-redirects.rst
Labels: Needed: documentation, Bug

#10149 Put back template_name on proxito 404 view
  readthedocs/proxito/views/serve.py
Labels: PR: hotfix

#10131 Docs: New how-to sublevels (Diátaxis)
  docs/dev/style-guide.rst
  docs/user/connected-accounts.rst
  docs/user/guides/access/index.rst
  docs/user/guides/administrators.rst
  docs/user/guides/authors.rst
  docs/user/guides/best-practice/index.rst
  docs/user/guides/best-practice/links.rst
  docs/user/guides/build-troubleshooting.rst
  docs/user/guides/build-using-too-many-resources.rst
  docs/user/guides/build/index.rst
  docs/user/guides/content/index.rst
  docs/user/guides/deprecating-content.rst
  docs/user/guides/developers.rst
  docs/user/guides/embedding-content.rst
  docs/user/guides/git-integrations.rst
  docs/user/guides/importing-private-repositories.rst
  docs/user/guides/index.rst
  docs/user/guides/maintenance/index.rst
  docs/user/guides/management/index.rst
  docs/user/guides/pdf-non-ascii-languages.rst
  docs/user/guides/private-submodules.rst
  docs/user/guides/redirects.rst
  docs/user/guides/setup/index.rst
  docs/user/guides/technical-docs-seo-guide.rst
  docs/user/guides/troubleshooting/index.rst
  docs/user/index.rst
  docs/user/reference/features.rst
  docs/user/user-defined-redirects.rst
Labels: Improvement, Needed: documentation

#10158 Revert 92a7182af42e26cab01265d2cc06fc7832832689
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/constants.py
  readthedocs/doc_builder/exceptions.py
  readthedocs/projects/tests/mockers.py
  readthedocs/projects/tests/test_build_tasks.py
Labels: PR: hotfix

#10186 Docs: Changes to main index page (Diátaxis)
  docs/user/examples.rst
  docs/user/guides/cross-referencing-with-sphinx.rst
  docs/user/guides/index.rst
  docs/user/index.rst
  docs/user/tutorial/index.rst
  docs/user/tutorials/index.rst
Labels: Improvement, Needed: documentation
