Repository readthedocs/readthedocs.org, pull requests merged in 2023-02, with the labels that each got.

#9654 Do not assign html_theme_path
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
  readthedocs/projects/models.py
Labels: Bug

#9953 Docs: Split "Automation rules" into reference and how-to (Diátaxis)
  docs/user/automation-rules.rst
  docs/user/glossary.rst
  docs/user/guides/administrators.rst
  docs/user/guides/automation-rules.rst
  docs/user/img/screenshot_automation_rules_add.png
  docs/user/index.rst
  docs/user/reference/features.rst
Labels: Improvement, Needed: documentation

#10004 Docs: Relabel SEO guide as explanation (Diátaxis)
  docs/user/glossary.rst
  docs/user/guides/administrators.rst
  docs/user/guides/technical-docs-seo-guide.rst
  docs/user/index.rst
Labels: Improvement, Needed: documentation

#9966 Docs: Refactor "Environment variables" into 3 articles (Diátaxis)
  docs/user/build-customization.rst
  docs/user/builds.rst
  docs/user/environment-variables.rst
  docs/user/guides/administrators.rst
  docs/user/guides/environment-variables.rst
  docs/user/img/screenshot_environment_variables.png
  docs/user/index.rst
  docs/user/reference/environment-variables.rst
Labels: Improvement, Needed: documentation

#9952 Docs: Relabel and reorganize hosting features as reference (Diátaxis)
  docs/user/hosting.rst
  docs/user/index.rst
  docs/user/reference/404-not-found.rst
  docs/user/reference/cdn.rst
  docs/user/reference/features.rst
  docs/user/reference/robots.rst
  docs/user/reference/sitemaps.rst
Labels: Improvement, Needed: documentation

#10010 Docs: Navigation menu wrap-up: About, Features and Advanced Features as Reference (Diátaxis)
  docs/user/about/index.rst
  docs/user/features.rst
  docs/user/index.rst
  docs/user/reference/features.rst
Labels: Improvement, Needed: documentation

#10026 Docs: Navigation reorder (Diátaxis)
  docs/conf.py
  docs/user/about/index.rst
  docs/user/api/index.rst
  docs/user/build-default-versions.rst
  docs/user/commercial/sharing.rst
  docs/user/connected-accounts.rst
  docs/user/features.rst
  docs/user/guides/administrators.rst
  docs/user/guides/authors.rst
  docs/user/guides/build-troubleshooting.rst
  docs/user/guides/build-using-too-many-resources.rst
  docs/user/guides/developers.rst
  docs/user/guides/index.rst
  docs/user/guides/troubleshooting/index.rst
  docs/user/index.rst
  docs/user/integrations.rst
  docs/user/pull-requests.rst
  docs/user/reference/features.rst
  docs/user/reference/policies.rst
  docs/user/science.rst
  docs/user/shared/contribute-to-troubleshooting.rst
  docs/user/single-version.rst
  docs/user/tutorial/index.rst
Labels: Improvement, Needed: documentation

#10052 Revert "Requirements: unpin `newrelic` (#10041)"
  requirements/deploy.in
  requirements/deploy.txt
Labels: PR: hotfix

#10060 Support delisting of projects
  readthedocs/projects/migrations/0096_add_project_delisted.py
  readthedocs/projects/models.py
  readthedocs/proxito/views/serve.py
  readthedocs/search/documents.py
  readthedocs/templates/core/project_bar_base.html
  readthedocs/templates/robots.delisted.txt
Labels: Feature, Accepted

#10081 Migration edit: Allow null values in field "Project.delisted"
  readthedocs/projects/migrations/0096_add_project_delisted.py
  readthedocs/projects/models.py
Labels: PR: hotfix
