Repository readthedocs/readthedocs.org, pull requests merged in 2023-04, with the labels that each got.

#10245 Scripts: Add export statements and instruction to fetch awscli (compile_version_upload_s3.sh)
  scripts/compile_version_upload_s3.sh
Labels: Improvement

#10259 Revert "Proxito: inject hosting integration header for `build.commands` (#10219)"
  readthedocs/proxito/middleware.py
Labels: PR: hotfix

#10249 Docs: New entries to glossary
  docs/user/build-notifications.rst
  docs/user/connected-accounts.rst
  docs/user/faq.rst
  docs/user/glossary.rst
  docs/user/guides/build-notifications.rst
  docs/user/guides/git-integrations.rst
  docs/user/guides/reproducible-builds.rst
  docs/user/tutorial/index.rst
Labels: Improvement, Needed: documentation
