Repository readthedocs/readthedocs.org, pull requests merged in 2023-06, with the labels that each got.

#10396 Docs: Split email notifications and webhook notifications into separate howtos
  docs/user/build-notifications.rst
  docs/user/guides/build/email-notifications.rst
  docs/user/guides/build/index.rst
  docs/user/guides/build/webhooks.rst
  docs/user/guides/setup/git-repo-manual.rst
Labels: Improvement

#10393 Project: Add deprecation and removal warning to Advanced Settings
  readthedocs/templates/projects/project_advanced_settings_helptext.html
Labels: Design

#10407 Docs: Add $READTHEDOCS_OUTPUT to environment variable reference
  docs/user/reference/environment-variables.rst
Labels: Improvement

#10432 Deprecation: show the project slug/link correctly on email
  readthedocs/projects/tasks/utils.py
Labels: PR: hotfix

#10431 Add the api_client into the sync_repo task
  readthedocs/projects/tasks/builds.py
Labels: PR: hotfix

#10435 Docs: Add email template to report abandoned projects
  docs/user/abandoned-projects.rst
Labels: Improvement

#10443 Do not show paths in 404s
  readthedocs/templates/errors/404/include_error_message.html
Labels: Improvement

#8052 Flyout and Footer API design document
  docs/_static/images/design-docs/flyout/flask-versions-mockup.png
  docs/_static/images/design-docs/flyout/flyout-expanded.png
  docs/development/design/flyout-redesign.rst
Labels: Accepted

#10480 Images: Add tzdata as explicit requirement
  requirements/docker.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/testing.txt
Labels: Bug, dependencies
