Repository readthedocs/readthedocs.org, pull requests merged in 2023-01, with the labels that each got.

#9836 Docs: Relabel Organizations as Explanation (Diátaxis)
  docs/user/commercial/organizations.rst
  docs/user/guides/manage-read-the-docs-teams.rst
  docs/user/index.rst
Labels: Improvement, Needed: documentation

#9891 UI updates to Connected Accounts
  readthedocs/projects/static-src/projects/css/admin.less
  readthedocs/projects/static/projects/css/admin.css
  readthedocs/templates/socialaccount/connections.html
Labels: Improvement

#9834 Docs: Relabel and move explanation and how-tos around OAuth (Diátaxis)
  docs/user/connected-accounts.rst
  docs/user/guides/administrators.rst
  docs/user/guides/connecting-git-account.rst
  docs/user/img/oauth_github_dialog.png
  docs/user/img/screenshot_connected_services.png
  docs/user/index.rst
  docs/user/intro/import-guide.rst
Labels: Improvement, Needed: documentation

#9908 Docs: Move and update FAQ (Diátaxis)
  docs/user/faq.rst
  docs/user/index.rst
Labels: Needed: documentation

#9949 Docs: Make the GSOC page orphaned (Diátaxis)
  docs/user/gsoc.rst
  docs/user/index.rst
Labels: Improvement, Needed: documentation

#9951 Docs: Relabel badges as feature reference (Diátaxis)
  docs/user/badges.rst
  docs/user/index.rst
  docs/user/reference/features.rst
Labels: Improvement, Needed: documentation

#9914 Docs: Add new section "How-to / Troubleshooting" and move 2 existing troubleshooting pages
  docs/user/faq.rst
  docs/user/guides/build-troubleshooting.rst
  docs/user/guides/build-using-too-many-resources.rst
  docs/user/guides/troubleshooting/index.rst
  docs/user/index.rst
  docs/user/shared/contribute_to_troubleshooting.rst
Labels: Needed: documentation

#9893 CI: Add option `--show-diff-on-failure` to pre-commit
  tox.ini
Labels: Improvement

#9915 Docs: Move Main Features and Feature Flags to "Reference/Features" (Diátaxis)
  docs/user/feature-flags.rst
  docs/user/index.rst
  docs/user/reference/features.rst
Labels: Needed: documentation

#9916 Docs: Relabel pages to new top-level "Reference/Policies and legal documents" (Diátaxis)
  docs/user/abandoned-projects.rst
  docs/user/index.rst
  docs/user/legal/index.rst
  docs/user/legal/security-policy.rst
  docs/user/privacy-policy.rst
  docs/user/reference/policies.rst
  docs/user/security.rst
  docs/user/unofficial-projects.rst
Labels: Needed: documentation

#8031 Make Build models default to `triggered`
  readthedocs/builds/migrations/0047_build_default_triggered.py
  readthedocs/builds/models.py
  readthedocs/builds/tests/test_views.py
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_project_views.py
  readthedocs/rtd_tests/tests/test_version_config.py
Labels: Good First Issue, Accepted
