Repository readthedocs/readthedocs.org, pull requests merged in 2023-08, with the labels that each got.

#10614 Revert "Proxito: test new implementation more broadly (#10599)"
  readthedocs/api/v2/serializers.py
  readthedocs/projects/models.py
  readthedocs/proxito/middleware.py
  readthedocs/proxito/views/serve.py
  readthedocs/rtd_tests/tests/test_backend.py
Labels: PR: hotfix

#10613 Translations: update them all
  readthedocs/locale/ar/LC_MESSAGES/django.po
  readthedocs/locale/ca/LC_MESSAGES/django.po
  readthedocs/locale/de/LC_MESSAGES/django.po
  readthedocs/locale/en/LC_MESSAGES/django.po
  readthedocs/locale/es/LC_MESSAGES/django.po
  readthedocs/locale/eu/LC_MESSAGES/django.po
  readthedocs/locale/fr/LC_MESSAGES/django.po
  readthedocs/locale/gl/LC_MESSAGES/django.po
  readthedocs/locale/he/LC_MESSAGES/django.po
  readthedocs/locale/hu/LC_MESSAGES/django.po
  readthedocs/locale/id_ID/LC_MESSAGES/django.po
  readthedocs/locale/it/LC_MESSAGES/django.po
  readthedocs/locale/ja/LC_MESSAGES/django.po
  readthedocs/locale/ko_KR/LC_MESSAGES/django.po
  readthedocs/locale/lt/LC_MESSAGES/django.po
  readthedocs/locale/nb/LC_MESSAGES/django.po
  readthedocs/locale/nl/LC_MESSAGES/django.po
  readthedocs/locale/nl_NL/LC_MESSAGES/django.po
  readthedocs/locale/pl/LC_MESSAGES/django.po
  readthedocs/locale/pt_BR/LC_MESSAGES/django.po
  readthedocs/locale/ru/LC_MESSAGES/django.po
  readthedocs/locale/sk/LC_MESSAGES/django.po
  readthedocs/locale/tr/LC_MESSAGES/django.po
  readthedocs/locale/uk/LC_MESSAGES/django.po
  readthedocs/locale/vi_VN/LC_MESSAGES/django.po
  readthedocs/locale/zh_CN/LC_MESSAGES/django.po
  readthedocs/locale/zh_TW/LC_MESSAGES/django.po
Labels: PR: hotfix

#10618 Revert "Contact projects with a build in the last 3 years"
  readthedocs/projects/tasks/utils.py
  readthedocs/templates/projects/notifications/deprecated_config_file_used_email.html
  readthedocs/templates/projects/notifications/deprecated_config_file_used_email.txt
Labels: Status: blocked

#8968 VCS: remove unused methods and make new Git pattern the default
  readthedocs/projects/models.py
  readthedocs/projects/tasks/mixins.py
  readthedocs/projects/tests/mockers.py
  readthedocs/projects/tests/test_build_tasks.py
  readthedocs/rtd_tests/tests/test_backend.py
  readthedocs/vcs_support/backends/__init__.py
  readthedocs/vcs_support/backends/bzr.py
  readthedocs/vcs_support/backends/git.py
  readthedocs/vcs_support/backends/hg.py
  readthedocs/vcs_support/backends/svn.py
  readthedocs/vcs_support/base.py
  requirements/deploy.txt
  requirements/docker.txt
  requirements/pip.in
  requirements/pip.txt
  requirements/testing.txt
Labels: Accepted

#10653 Build: remove `using_rtd_theme` variable
  readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl
Labels: PR: hotfix

#5609 Stop creating a conf.py automatically and doing magic around README handling
  readthedocs/doc_builder/backends/mkdocs.py
  readthedocs/doc_builder/backends/sphinx.py
  readthedocs/doc_builder/base.py
  readthedocs/doc_builder/exceptions.py
  readthedocs/projects/utils.py
  readthedocs/rtd_tests/tests/test_doc_builder.py
Labels: Status: blocked

#10562 Deprecation: remove "use system packages" (`python.system_packages` config key and UI checkbox)
  docs/user/api/v3.rst
  docs/user/config-file/v1.rst
  docs/user/config-file/v2.rst
  readthedocs/api/v2/serializers.py
  readthedocs/config/config.py
  readthedocs/config/models.py
  readthedocs/config/tests/test_config.py
  readthedocs/doc_builder/config.py
  readthedocs/doc_builder/python_environments.py
  readthedocs/projects/fixtures/test_data.json
  readthedocs/projects/forms.py
  readthedocs/projects/models.py
  readthedocs/projects/tests/test_build_tasks.py
  readthedocs/rtd_tests/fixtures/spec/v2/schema.json
  readthedocs/rtd_tests/fixtures/spec/v2/schema.yml
  readthedocs/rtd_tests/tests/test_api.py
  readthedocs/rtd_tests/tests/test_build_config.py
  readthedocs/rtd_tests/tests/test_config_integration.py
  readthedocs/rtd_tests/tests/test_doc_building.py
  readthedocs/templates/builds/build_detail.html
Labels: Status: blocked
